apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3  # Number of desired replicas/pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Using the latest Nginx image from Docker Hub
          ports:
            - containerPort: 8080  # Nginx listens on port 8080 inside the container
